server:
  port: 8000

spring:
  application:
    name: api-gateway

jwt:
  secret: ${JWT_SECRET:c0c08bac4d23ad90d896132081729e44aedcc619f94906e7b16a7624bc791d41}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus