# Server configuration
server.port=8000
spring.application.name=api-gateway

# Route 0: Event Service
spring.cloud.gateway.server.webflux.routes[0].id=event-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://nginx-lb:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/events/**,/whoami

# Route 1: Order Service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://order-service:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**,/users/**

# Route 2: Notification Service
spring.cloud.gateway.server.webflux.routes[2].id=notification-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://notification-service:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/notifications/**