events {}

http {
    upstream event_service_backend {
        # Docker DNS resolves these to the container IPs
        server event-service-1:8080;
        server event-service-2:8080;
        # round-robin by default
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://event_service_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}